import type { TemplateRegistry } from "../registry/types.js";

export type SupportedShell = "bash" | "zsh" | "fish";

const SHELLS: SupportedShell[] = ["bash", "zsh", "fish"];

const HEADER = `# Generated by qorrol completion. Do not edit by hand.
# Source this file (bash), drop it in \$fpath (zsh), or save to
# ~/.config/fish/completions/ (fish). See \`qorrol completion --help\`.
`;

function bashScript(templateNames: string): string {
  return `${HEADER}
_qorrol_completion() {
  local cur prev cmds
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  if [[ \${COMP_CWORD} -eq 1 ]]; then
    cmds="create list ps completion help"
    COMPREPLY=( $(compgen -W "\${cmds}" -- "\${cur}") )
    return 0
  fi

  case "\${COMP_WORDS[1]}" in
    create)
      if [[ \${cur} == -* ]]; then
        COMPREPLY=( $(compgen -W "-n --name -h --help" -- "\${cur}") )
      else
        COMPREPLY=( $(compgen -W "${templateNames}" -- "\${cur}") )
      fi
      ;;
    ps)
      COMPREPLY=( $(compgen -W "-e --exclude -t --timeout --json -h --help" -- "\${cur}") )
      ;;
    completion)
      COMPREPLY=( $(compgen -W "bash zsh fish" -- "\${cur}") )
      ;;
    *)
      COMPREPLY=( $(compgen -W "-h --help -V --version" -- "\${cur}") )
      ;;
  esac
}
complete -F _qorrol_completion qorrol
`;
}

function zshScript(registry: TemplateRegistry): string {
  const tmpls = registry
    .list()
    .map((t) => `'${t.name}:${t.description.replace(/'/g, "'\\''")}'`)
    .join(" ");
  return `${HEADER}
#compdef qorrol
_qorrol() {
  local -a commands
  commands=(
    'create:Create a new project from a template'
    'list:List available templates'
    'ps:Snapshot running processes (bounded time, no wait on watchers)'
    'completion:Output a shell completion script'
    'help:Display help for a command'
  )

  _arguments -C \\
    '1: :->cmd' \\
    '*:: :->args'

  case "\$state" in
    cmd)
      _describe -t commands 'qorrol command' commands
      ;;
    args)
      case "\$words[1]" in
        create)
          _arguments \\
            '1: :->template' \\
            '-n[Project directory name]:name:' \\
            '--name[Project directory name]:name:'
          if [[ "\$state" == template ]]; then
            local -a tmpls
            tmpls=(${tmpls})
            _describe -t templates 'template' tmpls
          fi
          ;;
        ps)
          _arguments \\
            '-e[Comma-separated command substrings to exclude]:patterns:' \\
            '--exclude[Comma-separated command substrings to exclude]:patterns:' \\
            '-t[Snapshot timeout in milliseconds]:ms:' \\
            '--timeout[Snapshot timeout in milliseconds]:ms:' \\
            '--json[Print JSON output]'
          ;;
        completion)
          _arguments '1: :(bash zsh fish)'
          ;;
      esac
      ;;
  esac
}
_qorrol "\$@"
`;
}

function fishScript(registry: TemplateRegistry): string {
  const tmpls = registry
    .list()
    .map(
      (t) =>
        `complete -c qorrol -n "__fish_use_subcommand" -a "${t.name.replace(/"/g, '\\"')}" -d "${t.description.replace(/"/g, '\\"')}"`,
    )
    .join("\n");
  return `${HEADER}
function __qorrol_list_subcommands
  echo "create\tCreate a new project from a template"
  echo "list\tList available templates"
  echo "ps\tSnapshot running processes (bounded time, no wait on watchers)"
  echo "completion\tOutput a shell completion script"
  echo "help\tDisplay help for a command"
end

# Top-level commands
complete -c qorrol -f -n "__fish_use_subcommand" -a "(__qorrol_list_subcommands)"

# create subcommand
complete -c qorrol -f -n "__fish_seen_subcommand_from create" -l name -s n -d "Project directory name"
${tmpls}

# ps subcommand
complete -c qorrol -f -n "__fish_seen_subcommand_from ps" -l exclude -s e -d "Comma-separated command substrings to exclude"
complete -c qorrol -f -n "__fish_seen_subcommand_from ps" -l timeout -s t -d "Snapshot timeout in milliseconds"
complete -c qorrol -f -n "__fish_seen_subcommand_from ps" -l json -d "Print JSON output"

# completion subcommand
complete -c qorrol -f -n "__fish_seen_subcommand_from completion" -a "bash zsh fish"
`;
}

export function getCompletionScript(
  shell: string,
  registry: TemplateRegistry,
): string {
  if (!SHELLS.includes(shell as SupportedShell)) {
    throw new Error(
      `Unsupported shell "${shell}". Supported: ${SHELLS.join(", ")}`,
    );
  }
  const templateNames = registry
    .list()
    .map((t) => t.name)
    .join(" ");
  switch (shell as SupportedShell) {
    case "bash":
      return bashScript(templateNames);
    case "zsh":
      return zshScript(registry);
    case "fish":
      return fishScript(registry);
  }
}

export function listSupportedShells(): SupportedShell[] {
  return SHELLS;
}
