import type { TemplateRegistry } from "../registry/types.js";

export type SupportedShell = "bash" | "zsh" | "fish";

const SHELLS: SupportedShell[] = ["bash", "zsh", "fish"];

const TOP_LEVEL =
  "create list resolve doctor ps issues request completion help";

const HEADER = [
  "# Generated by qorrol completion. Do not edit by hand.",
  "# Source this file (bash), drop it in $fpath (zsh), or save it to",
  "# ~/.config/fish/completions/ (fish). See `qorrol completion --help`.",
  "",
].join("\n");

function bashScript(templateNames: string): string {
  return `${HEADER}
_qorrol_completion() {
  local cur prev cmds
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  if [[ \${COMP_CWORD} -eq 1 ]]; then
    cmds="${TOP_LEVEL}"
    COMPREPLY=( $(compgen -W "\${cmds}" -- "\${cur}") )
    return 0
  fi

  case "\${COMP_WORDS[1]}" in
    create)
      if [[ \${cur} == -* ]]; then
        COMPREPLY=( $(compgen -W "-n --name --dry-run --json -h --help" -- "\${cur}") )
      else
        COMPREPLY=( $(compgen -W "${templateNames}" -- "\${cur}") )
      fi
      ;;
    resolve)
      COMPREPLY=( $(compgen -W "${templateNames} --json -h --help" -- "\${cur}") )
      ;;
    list|doctor)
      COMPREPLY=( $(compgen -W "--json -h --help" -- "\${cur}") )
      ;;
    ps)
      COMPREPLY=( $(compgen -W "-e --exclude -t --timeout --json -h --help" -- "\${cur}") )
      ;;
    issues)
      if [[ \${COMP_CWORD} -eq 2 ]]; then
        COMPREPLY=( $(compgen -W "list view attention comment label close" -- "\${cur}") )
      else
        COMPREPLY=( $(compgen -W "--json --limit --label --body --body-file --add --remove --comment --dry-run -h --help" -- "\${cur}") )
      fi
      ;;
    request)
      COMPREPLY=( $(compgen -W "--json --write -h --help" -- "\${cur}") )
      ;;
    completion)
      COMPREPLY=( $(compgen -W "bash zsh fish" -- "\${cur}") )
      ;;
    *)
      COMPREPLY=( $(compgen -W "-h --help -V --version --json" -- "\${cur}") )
      ;;
  esac
}
complete -F _qorrol_completion qorrol
`;
}

function zshScript(registry: TemplateRegistry): string {
  const tmpls = registry
    .list()
    .map((t) => `'${t.name}:${t.description.replace(/'/g, "'\\''")}'`)
    .join(" ");
  return `${HEADER}
#compdef qorrol
_qorrol() {
  local -a commands
  commands=(
    'create:Create a new project from a template'
    'list:List available templates'
    'resolve:Resolve a template name to its registry record'
    'doctor:Verify setup, templates, and optional GitHub auth'
    'ps:Snapshot running processes (bounded time, no wait on watchers)'
    'issues:Read and write GitHub issues via gh'
    'request:Raw gh CLI escape hatch'
    'completion:Output a shell completion script'
    'help:Display help for a command'
  )

  _arguments -C \\
    '--json[Print a stable JSON envelope to stdout]' \\
    '1: :->cmd' \\
    '*:: :->args'

  case "\$state" in
    cmd)
      _describe -t commands 'qorrol command' commands
      ;;
    args)
      case "\$words[1]" in
        create)
          _arguments \\
            '1: :->template' \\
            '-n[Project directory name]:name:' \\
            '--name[Project directory name]:name:' \\
            '--dry-run[Validate without cloning]' \\
            '--json[Print JSON envelope]'
          if [[ "\$state" == template ]]; then
            local -a tmpls
            tmpls=(${tmpls})
            _describe -t templates 'template' tmpls
          fi
          ;;
        resolve)
          local -a tmpls
          tmpls=(${tmpls})
          _describe -t templates 'template' tmpls
          ;;
        list|doctor)
          _arguments '--json[Print JSON envelope]'
          ;;
        ps)
          _arguments \\
            '-e[Comma-separated command substrings to exclude]:patterns:' \\
            '--exclude[Comma-separated command substrings to exclude]:patterns:' \\
            '-t[Snapshot timeout in milliseconds]:ms:' \\
            '--timeout[Snapshot timeout in milliseconds]:ms:' \\
            '--json[Print JSON envelope]'
          ;;
        issues)
          _arguments \\
            '1: :(list view attention comment label close)' \\
            '--json[Print JSON envelope]' \\
            '--dry-run[Preview write without applying]'
          ;;
        request)
          _arguments '--write[Allow mutating gh commands]' '--json[Print JSON envelope]'
          ;;
        completion)
          _arguments '1: :(bash zsh fish)'
          ;;
      esac
      ;;
  esac
}
_qorrol "\$@"
`;
}

function fishScript(registry: TemplateRegistry): string {
  const tmpls = registry
    .list()
    .map(
      (t) =>
        `complete -c qorrol -f -n "__fish_seen_subcommand_from create resolve" -a "${t.name.replace(/"/g, '\\"')}" -d "${t.description.replace(/"/g, '\\"')}"`,
    )
    .join("\n");
  return `${HEADER}
function __qorrol_list_subcommands
  echo "create\\tCreate a new project from a template"
  echo "list\\tList available templates"
  echo "resolve\\tResolve a template name to its registry record"
  echo "doctor\\tVerify setup, templates, and optional GitHub auth"
  echo "ps\\tSnapshot running processes (bounded time, no wait on watchers)"
  echo "issues\\tRead and write GitHub issues via gh"
  echo "request\\tRaw gh CLI escape hatch"
  echo "completion\\tOutput a shell completion script"
  echo "help\\tDisplay help for a command"
end

# Top-level commands
complete -c qorrol -f -n "__fish_use_subcommand" -a "(__qorrol_list_subcommands)"
complete -c qorrol -l json -d "Print a stable JSON envelope to stdout"

# create subcommand
complete -c qorrol -f -n "__fish_seen_subcommand_from create" -l name -s n -d "Project directory name"
complete -c qorrol -f -n "__fish_seen_subcommand_from create" -l dry-run -d "Validate without cloning"
complete -c qorrol -f -n "__fish_seen_subcommand_from create" -l json -d "Print JSON envelope"
${tmpls}

# list / doctor / resolve
complete -c qorrol -f -n "__fish_seen_subcommand_from list doctor resolve" -l json -d "Print JSON envelope"

# ps subcommand
complete -c qorrol -f -n "__fish_seen_subcommand_from ps" -l exclude -s e -d "Comma-separated command substrings to exclude"
complete -c qorrol -f -n "__fish_seen_subcommand_from ps" -l timeout -s t -d "Snapshot timeout in milliseconds"
complete -c qorrol -f -n "__fish_seen_subcommand_from ps" -l json -d "Print JSON envelope"

# issues
complete -c qorrol -f -n "__fish_seen_subcommand_from issues" -a "list view attention comment label close"
complete -c qorrol -f -n "__fish_seen_subcommand_from issues" -l json -d "Print JSON envelope"
complete -c qorrol -f -n "__fish_seen_subcommand_from issues" -l dry-run -d "Preview write without applying"

# request
complete -c qorrol -f -n "__fish_seen_subcommand_from request" -l write -d "Allow mutating gh commands"
complete -c qorrol -f -n "__fish_seen_subcommand_from request" -l json -d "Print JSON envelope"

# completion subcommand
complete -c qorrol -f -n "__fish_seen_subcommand_from completion" -a "bash zsh fish"
`;
}

export function getCompletionScript(
  shell: string,
  registry: TemplateRegistry,
): string {
  if (!SHELLS.includes(shell as SupportedShell)) {
    throw new Error(
      `Unsupported shell "${shell}". Supported: ${SHELLS.join(", ")}`,
    );
  }
  const templateNames = registry
    .list()
    .map((t) => t.name)
    .join(" ");
  switch (shell as SupportedShell) {
    case "bash":
      return bashScript(templateNames);
    case "zsh":
      return zshScript(registry);
    case "fish":
      return fishScript(registry);
  }
}

export function listSupportedShells(): SupportedShell[] {
  return SHELLS;
}
